import type { Course, Book, Popup, Settings } from "../_types";

// ─── Mock Courses ─────────────────────────────────────────────────────────────

export const MOCK_COURSES: Course[] = [
  {
    id: "c1",
    title: "Lớp Căn Bản 1 (Pre A1 - Pre A2)",
    slug: "lop-can-ban-1-pre-a1-pre-a2",
    level: "Beginner",
    duration: "8 tuần",
    students: 245,
    price: 2299000,
    salePrice: 1999000,
    status: "Active",
    createdAt: "2026-01-10",
    image: "",
    category: "Tiếng Anh",
    courseCategory: "Căn Bản",
    teacher: "Nguyễn Thị Lan",
    description: "Khóa học dành cho người mới bắt đầu học tiếng Anh, tập trung vào từ vựng cơ bản và ngữ pháp sơ cấp.",
    introduction: "Chào mừng bạn đến với khóa học Lớp Căn Bản 1! Khóa học này được thiết kế dành cho người hoàn toàn chưa có nền tảng tiếng Anh hoặc mới bắt đầu.",
    benefits: "- Nắm vững bảng chữ cái tiếng Anh\n- Tự giới thiệu bản thân bằng tiếng Anh\n- Giao tiếp cơ bản trong cuộc sống hàng ngày\n- Xây dựng vốn từ vựng khoảng 500 từ thông dụng",
    purchaseNotes: "- Học phí đã bao gồm tài liệu học tập\n- Được tham gia nhóm hỗ trợ học tập\n- Hoàn tiền trong 7 ngày nếu không hài lòng",
  },
  {
    id: "c2",
    title: "Lớp Căn Bản 2 (A1 - A2)",
    slug: "lop-can-ban-2-a1-a2",
    level: "Beginner",
    duration: "8 tuần",
    students: 198,
    price: 2299000,
    salePrice: 0,
    status: "Active",
    createdAt: "2026-01-12",
    image: "",
    category: "Tiếng Anh",
    courseCategory: "Căn Bản",
    teacher: "Trần Văn Minh",
    description: "Khóa học tiếp nối Lớp Căn Bản 1, nâng cao kỹ năng ngữ pháp và từ vựng.",
    introduction: "Khóa học Lớp Căn Bản 2 giúp bạn củng cố và phát triển nền tảng tiếng Anh đã có.",
    benefits: "- Mở rộng vốn từ vựng lên 800-1000 từ\n- Sử dụng được các thì cơ bản\n- Đọc hiểu câu đơn giản\n- Viết câu hoàn chỉnh",
    purchaseNotes: "- Cần hoàn thành Lớp Căn Bản 1 hoặc đạt bài test đầu vào",
  },
  {
    id: "c3",
    title: "Lớp Trung Cấp 1 (Pre B1 - Mid B1)",
    slug: "lop-trung-cap-1-pre-b1-mid-b1",
    level: "Intermediate",
    duration: "10 tuần",
    students: 156,
    price: 3093000,
    salePrice: 2793000,
    status: "Active",
    createdAt: "2026-01-15",
    image: "",
    category: "Tiếng Anh",
    courseCategory: "Trung Cấp",
    teacher: "Lê Thị Hương",
    description: "Khóa học dành cho người đã có nền tảng cơ bản, hướng tới trình độ B1.",
    introduction: "Lớp Trung Cấp 1 là bước chuyển tiếp quan trọng từ A2 lên B1.",
    benefits: "- Nắm vững ngữ pháp nâng cao\n- Giao tiếp tự tin hơn\n- Đọc hiểu bài văn ngắn\n- Viết đoạn văn có logic",
    purchaseNotes: "- Yêu cầu trình độ A2 trở lên",
  },
  {
    id: "c4",
    title: "Lớp Trung Cấp 2 (Mid B1 - Upper B1)",
    slug: "lop-trung-cap-2-mid-b1-upper-b1",
    level: "Intermediate",
    duration: "10 tuần",
    students: 132,
    price: 3093000,
    salePrice: 0,
    status: "Active",
    createdAt: "2026-01-18",
    image: "",
    category: "Tiếng Anh",
    courseCategory: "Trung Cấp",
    teacher: "Phạm Đức Anh",
    description: "Hoàn thiện trình độ B1, chuẩn bị cho các khóa học nâng cao.",
    introduction: "Khóa học giúp bạn đạt trình độ B1 vững chắc.",
    benefits: "- Tự tin giao tiếp trong công việc\n- Đọc hiểu email, tài liệu\n- Viết report đơn giản",
    purchaseNotes: "- Cần hoàn thành Trung Cấp 1",
  },
  {
    id: "c5",
    title: "Lớp Cận Bản 3 (Mid A2 - Upper A2)",
    slug: "lop-can-ban-3-mid-a2-upper-a2",
    level: "Beginner",
    duration: "8 tuần",
    students: 110,
    price: 2299000,
    salePrice: 1899000,
    status: "Active",
    createdAt: "2026-01-20",
    image: "",
    category: "Tiếng Anh",
    courseCategory: "Căn Bản",
    teacher: "Nguyễn Thị Lan",
    description: "Khóa học bổ sung kiến thức A2, hoàn thiện nền tảng căn bản.",
    introduction: "Lớp Cận Bản 3 giúp bạn hoàn thiện trình độ A2.",
    benefits: "- Hoàn thiện ngữ pháp A2\n- Tăng vốn từ vựng lên 1500+ từ",
    purchaseNotes: "- Dành cho người đã hoàn thành Căn Bản 2",
  },
  {
    id: "c6",
    title: "IELTS Foundation Class",
    slug: "ielts-foundation-class",
    level: "Advanced",
    duration: "12 tuần",
    students: 85,
    price: 4500000,
    salePrice: 3999000,
    status: "Draft",
    createdAt: "2026-02-01",
    image: "",
    category: "IELTS",
    courseCategory: "IELTS",
    teacher: "Trần Văn Minh",
    description: "Khóa học chuẩn bị kiến thức nền tảng cho IELTS, phù hợp với người mới bắt đầu học IELTS.",
    introduction: "IELTS Foundation Class là khóa học dành cho những ai muốn bắt đầu hành trình chinh phục IELTS.",
    benefits: "- Làm quen với format IELTS\n- Học chiến lược làm bài thi\n- Luyện tập 4 kỹ năng",
    purchaseNotes: "- Yêu cầu trình độ B1 trở lên\n- Cần mua sách luyện IELTS",
  },
];

// ─── Mock Books ───────────────────────────────────────────────────────────────

export const MOCK_BOOKS: Book[] = [
  {
    id: "b1",
    title: "Fun English for Kids",
    author: "Telesa Academic Team",
    isbn: "978-0000000001",
    category: "Kids",
    price: 120000,
    stock: 120,
    status: "In Stock",
    publishedAt: "2025-09-01",
  },
  {
    id: "b2",
    title: "Cambridge English Fun for Starters",
    author: "Cambridge Press",
    isbn: "978-1108701657",
    category: "Kids",
    price: 180000,
    stock: 95,
    status: "In Stock",
    publishedAt: "2024-06-10",
  },
  {
    id: "b3",
    title: "Cambridge English Fun for Movers",
    author: "Cambridge Press",
    isbn: "978-1108701664",
    category: "Kids",
    price: 190000,
    stock: 60,
    status: "In Stock",
    publishedAt: "2024-06-10",
  },
  {
    id: "b4",
    title: "You Can Talk - TES Level 2 (Pre A1 - Pre A2)",
    author: "Telesa Academic Team",
    isbn: "978-0000000002",
    category: "Speaking",
    price: 150000,
    stock: 80,
    status: "In Stock",
    publishedAt: "2025-10-01",
  },
  {
    id: "b5",
    title: "You Can Talk - TES Level 2 (Pre A1 - Pre A2) - Audio",
    author: "Telesa Academic Team",
    isbn: "978-0000000003",
    category: "Speaking",
    price: 90000,
    stock: 200,
    status: "In Stock",
    publishedAt: "2025-10-01",
  },
];

// ─── Mock Popups ──────────────────────────────────────────────────────────────

export const MOCK_POPUPS: Popup[] = [
  {
    id: "p1",
    title: "Giảm học phí tháng 6",
    content: "Ưu đãi lên đến 13% cho tất cả lớp học tiếng Anh!",
    type: "Modal",
    targetPage: "Homepage",
    isActive: true,
    startDate: "2026-06-01",
    endDate: "2026-06-30",
  },
  {
    id: "p2",
    title: "Đăng ký học thử miễn phí",
    content: "Trải nghiệm lớp học 1-1 miễn phí 7 ngày.",
    type: "Banner",
    targetPage: "All Pages",
    isActive: true,
    startDate: "2026-04-01",
    endDate: "2026-12-31",
  },
  {
    id: "p3",
    title: "Khóa học mới",
    content: "IELTS & Communication class vừa mở đăng ký!",
    type: "Toast",
    targetPage: "Courses Page",
    isActive: false,
    startDate: "2026-03-01",
    endDate: "2026-04-01",
  },
];

// ─── Mock Settings ────────────────────────────────────────────────────────────

export const MOCK_SETTINGS: Settings = {
  email: "team1@telesaenglish.com",
  hotline: "0932639259",
};